version: '3'
services:
  # sonic:
  #   build: sonic
  #   stdin_open: true
  #   tty: true       
  base:
    build: base
    stdin_open: true
    tty: true       
  # python:
  #   build: python
  #   stdin_open: true
  #   tty: true       
  crystal:
    build: crystal
    stdin_open: true
    tty: true       
    depends_on: ["base"]
  golang:
    build: golang
    stdin_open: true
    tty: true       
    depends_on: ["base"]
  yggdrasil:
    build: yggdrasil
    stdin_open: true
    tty: true       
    depends_on: ["golang"]    
  # production:
  #   build: production
  #   stdin_open: true
  #   tty: true       
  #   depends_on: ["base","python"]    

   